services:
  - type: web
    name: whatsapp-bot
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn whatsapp_bot.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false